<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-08-10T03:30:00Z" name="Default suite" finished-at="2021-08-10T03:30:37Z" duration-ms="36721">
    <groups>
      <group name="regression">
        <method signature="TestCase2.verifyEducation()[pri:0, instance:batch_6_framework.TestCase2@2df3b89c]" name="verifyEducation" class="batch_6_framework.TestCase2"/>
        <method signature="TestCase2.verifyExpirence()[pri:15, instance:batch_6_framework.TestCase2@2df3b89c]" name="verifyExpirence" class="batch_6_framework.TestCase2"/>
      </group> <!-- regression -->
      <group name="sanity">
        <method signature="TestCase2.CreateUser()[pri:-5, instance:batch_6_framework.TestCase2@2df3b89c]" name="CreateUser" class="batch_6_framework.TestCase2"/>
        <method signature="TestCase2.NegativeTest()[pri:0, instance:batch_6_framework.TestCase2@2df3b89c]" name="NegativeTest" class="batch_6_framework.TestCase2"/>
        <method signature="TestCase2.verifyEducation()[pri:0, instance:batch_6_framework.TestCase2@2df3b89c]" name="verifyEducation" class="batch_6_framework.TestCase2"/>
        <method signature="TestCase2.verifyLogin()[pri:-1, instance:batch_6_framework.TestCase2@2df3b89c]" name="verifyLogin" class="batch_6_framework.TestCase2"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2021-08-10T03:30:00Z" name="Default test" finished-at="2021-08-10T03:30:37Z" duration-ms="36721">
      <class name="batch_6_framework.TestCase2">
        <test-method is-config="true" signature="startTest()[pri:0, instance:batch_6_framework.TestCase2@2df3b89c]" started-at="2021-08-10T03:30:00Z" name="startTest" finished-at="2021-08-10T03:30:03Z" duration-ms="2728" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="CreateUser()[pri:-5, instance:batch_6_framework.TestCase2@2df3b89c]" started-at="2021-08-10T03:30:03Z" name="CreateUser" finished-at="2021-08-10T03:30:03Z" duration-ms="347" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<invlaid creditial> but was:<invalid>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<invlaid creditial> but was:<invalid>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
at batch_6_framework.TestCase2.CreateUser(TestCase2.java:61)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateUser -->
        <test-method is-config="true" signature="endTest(org.testng.ITestResult)[pri:0, instance:batch_6_framework.TestCase2@2df3b89c]" started-at="2021-08-10T03:30:03Z" name="endTest" finished-at="2021-08-10T03:30:08Z" duration-ms="4407" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CreateUser status=FAILURE method=TestCase2.CreateUser()[pri:-5, instance:batch_6_framework.TestCase2@2df3b89c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method is-config="true" signature="startTest()[pri:0, instance:batch_6_framework.TestCase2@2df3b89c]" started-at="2021-08-10T03:30:08Z" name="startTest" finished-at="2021-08-10T03:30:10Z" duration-ms="2052" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="verifyLogin()[pri:-1, instance:batch_6_framework.TestCase2@2df3b89c]" started-at="2021-08-10T03:30:10Z" name="verifyLogin" finished-at="2021-08-10T03:30:10Z" duration-ms="270" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method is-config="true" signature="endTest(org.testng.ITestResult)[pri:0, instance:batch_6_framework.TestCase2@2df3b89c]" started-at="2021-08-10T03:30:10Z" name="endTest" finished-at="2021-08-10T03:30:14Z" duration-ms="4220" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLogin status=SUCCESS method=TestCase2.verifyLogin()[pri:-1, instance:batch_6_framework.TestCase2@2df3b89c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method is-config="true" signature="startTest()[pri:0, instance:batch_6_framework.TestCase2@2df3b89c]" started-at="2021-08-10T03:30:14Z" name="startTest" finished-at="2021-08-10T03:30:16Z" duration-ms="2105" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="NegativeTest()[pri:0, instance:batch_6_framework.TestCase2@2df3b89c]" started-at="2021-08-10T03:30:16Z" name="NegativeTest" finished-at="2021-08-10T03:30:17Z" duration-ms="367" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<invlaid creditial> but was:<invalid>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<invlaid creditial> but was:<invalid>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
at batch_6_framework.TestCase2.NegativeTest(TestCase2.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NegativeTest -->
        <test-method is-config="true" signature="endTest(org.testng.ITestResult)[pri:0, instance:batch_6_framework.TestCase2@2df3b89c]" started-at="2021-08-10T03:30:17Z" name="endTest" finished-at="2021-08-10T03:30:21Z" duration-ms="4439" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=NegativeTest status=FAILURE method=TestCase2.NegativeTest()[pri:0, instance:batch_6_framework.TestCase2@2df3b89c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method is-config="true" signature="startTest()[pri:0, instance:batch_6_framework.TestCase2@2df3b89c]" started-at="2021-08-10T03:30:21Z" name="startTest" finished-at="2021-08-10T03:30:25Z" duration-ms="3298" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="verifyEducation()[pri:0, instance:batch_6_framework.TestCase2@2df3b89c]" started-at="2021-08-10T03:30:25Z" name="verifyEducation" finished-at="2021-08-10T03:30:26Z" duration-ms="1135" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEducation -->
        <test-method is-config="true" signature="endTest(org.testng.ITestResult)[pri:0, instance:batch_6_framework.TestCase2@2df3b89c]" started-at="2021-08-10T03:30:26Z" name="endTest" finished-at="2021-08-10T03:30:30Z" duration-ms="4172" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyEducation status=SUCCESS method=TestCase2.verifyEducation()[pri:0, instance:batch_6_framework.TestCase2@2df3b89c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method is-config="true" signature="startTest()[pri:0, instance:batch_6_framework.TestCase2@2df3b89c]" started-at="2021-08-10T03:30:30Z" name="startTest" finished-at="2021-08-10T03:30:32Z" duration-ms="1985" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="verifyExpirence()[pri:15, instance:batch_6_framework.TestCase2@2df3b89c]" started-at="2021-08-10T03:30:32Z" name="verifyExpirence" finished-at="2021-08-10T03:30:33Z" duration-ms="1005" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExpirence -->
        <test-method is-config="true" signature="endTest(org.testng.ITestResult)[pri:0, instance:batch_6_framework.TestCase2@2df3b89c]" started-at="2021-08-10T03:30:33Z" name="endTest" finished-at="2021-08-10T03:30:37Z" duration-ms="4167" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyExpirence status=SUCCESS method=TestCase2.verifyExpirence()[pri:15, instance:batch_6_framework.TestCase2@2df3b89c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- batch_6_framework.TestCase2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
